# Generated by Django 2.2.7 on 2020-01-24 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unit', max_length=256)),
                ('measurement_type', models.CharField(default=None, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=256)),
                ('location', models.CharField(default=None, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='WellReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='untitled', max_length=256)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('graph', models.ImageField(default=None, upload_to='reports/%Y/%m/%d/')),
                ('mean', models.FloatField(default=None)),
                ('minimum', models.FloatField(default=None)),
                ('maximum', models.FloatField(default=None)),
                ('first', models.FloatField(default=None)),
                ('first_date', models.DateTimeField(null=True)),
                ('last', models.FloatField(default=None)),
                ('last_date', models.DateTimeField(null=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.Unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.Well')),
            ],
        ),
        migrations.CreateModel(
            name='WellReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_file', models.CharField(default=None, max_length=256, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('value', models.FloatField(default=None)),
                ('quality_code', models.FloatField(default=None, null=True)),
                ('tag_comments', models.CharField(default='', max_length=256)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.Unit')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.Well')),
            ],
        ),
        migrations.CreateModel(
            name='MetaReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='untitled', max_length=256)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('csv', models.FileField(default=None, upload_to='reports/%Y/%m/%d/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
