# Generated by Django 3.0.2 on 2020-02-14 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellreport',
            name='total_readings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wellreading',
            name='tag_comments',
            field=models.CharField(default='', max_length=256, null=True),
        ),
    ]
