# Generated by Django 3.0.2 on 2020-02-19 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellreading',
            name='tag_comments',
            field=models.CharField(default='', max_length=256, null=True),
        ),
    ]
