# Generated by Django 3.0.2 on 2020-02-19 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20200214_0301'),
        ('analysis', '0002_auto_20200219_0304'),
    ]

    operations = [
    ]
